#!/usr/bin/env python3
"""Generate Agent Skills folders under skills/ from the governance documents.

The governance documents stay the single source. Each skill is a folder with a
SKILL.md (YAML frontmatter `name` and `description`, then the copied text), in
the format Paperclip, Claude Code and Codex load. Paperclip imports copy only
the files inside a skill folder, so the text is copied, never linked.

Usage:
    python3 tools/build_skills.py          # write skills/
    python3 tools/build_skills.py --check  # exit 1 if skills/ is out of date

Only rules that apply when a task calls for them belong here. Rules that must
hold on every run stay in agent instructions: an agent sees a skill's name and
description and opens the body only when it judges the skill relevant.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILLS_DIR = ROOT / "skills"

# name, description, sources: (path relative to ROOT, heading or None for the whole file)
SKILLS: list[tuple[str, str, list[tuple[str, str | None]]]] = [
    (
        "workspace-document-contract",
        "Use when writing or checking a work item, instruction, report, review, decision or "
        "milestone document, or a prompt or report between roles: required header fields, "
        "vocabularies, the Blocked on shape, the execution envelope, the header and footer, "
        "and the handoff block.",
        [("governance/60-workspace-document-contract.md", None)],
    ),
    (
        "advisor-review",
        "Use when performing or commissioning an independent Advisor review of a product "
        "specification, an architecture or a product direction: the Advisor's authority, "
        "stance, what it receives, the Premise and Material tiers and the finding fields.",
        [
            ("governance/10-agents_workflow.md", "## Advisor"),
            ("governance/70-review-and-release.md", "## Advisor review"),
        ],
    ),
    (
        "review-and-release",
        "Use when dispositioning findings, checking or approving a release summary, writing a "
        "review with findings, answering review findings in a rework report, or accepting a "
        "technical or product milestone.",
        [
            ("governance/70-review-and-release.md", "## Dispositions of findings"),
            ("governance/70-review-and-release.md", "## Release"),
            ("governance/70-review-and-release.md", "## Reviews, rework and acceptance"),
        ],
    ),
    (
        "project-structure-tiers",
        "Use when creating a project, assigning or changing its governance tier, or checking "
        "which files, tests, CI and documentation a tier requires.",
        [("project_patterns/10-project-structure-tiers.md", None)],
    ),
    (
        "change-routing",
        "Use when a pull request is opened, is ready for review, or is about to be merged: classify it "
        "by path ownership into the technical or product route, split mixed pull requests, compile the "
        "Product Owner card, and merge only the approved head commit.",
        [("governance/80-change-routing.md", None)],
    ),
]

HEADING = re.compile(r"^(#{1,6}) ")


def extract(path: str, heading: str | None) -> str:
    text = (ROOT / path).read_text()
    if heading is None:
        return text.rstrip()
    lines = text.split("\n")
    starts = [i for i, line in enumerate(lines) if line.strip() == heading]
    if len(starts) != 1:
        raise SystemExit(f"{path}: heading {heading!r} found {len(starts)} times, expected 1")
    start = starts[0]
    level = len(HEADING.match(lines[start]).group(1))
    end = start + 1
    while end < len(lines):
        match = HEADING.match(lines[end])
        if match and len(match.group(1)) <= level:
            break
        end += 1
    return "\n".join(lines[start:end]).rstrip()


def render(name: str, description: str, sources: list[tuple[str, str | None]]) -> str:
    origin = ", ".join(f"`{path}`" + (f" ({heading.lstrip('# ')})" if heading else "") for path, heading in sources)
    body = "\n\n".join(extract(path, heading) for path, heading in sources)
    return (
        "---\n"
        f"name: {name}\n"
        f"description: >\n  {description}\n"
        "---\n\n"
        f"<!-- Generated by tools/build_skills.py from {origin}. Edit the sources, not this file. -->\n\n"
        f"{body}\n"
    )


def main() -> int:
    check = "--check" in sys.argv[1:]
    expected = {name: render(name, description, sources) for name, description, sources in SKILLS}
    stale: list[str] = []
    for name, content in expected.items():
        target = SKILLS_DIR / name / "SKILL.md"
        if target.exists() and target.read_text() == content:
            continue
        stale.append(name)
        if not check:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content)
    extra = sorted(p.name for p in SKILLS_DIR.iterdir() if p.is_dir() and p.name not in expected) if SKILLS_DIR.exists() else []
    if check:
        if stale or extra:
            print(f"skills out of date: {', '.join(stale + extra)}; run python3 tools/build_skills.py")
            return 1
        print("skills up to date")
        return 0
    for name in extra:
        print(f"warning: skills/{name} is not in the manifest; remove it by hand")
    print(f"wrote {len(stale)} skill(s)" if stale else "skills already up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
